spring:
  application:
    name: issue

managements:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

    metrics:
      tags:
        application: ${spring.application.name}
